# Generated by Django 5.2 on 2025-04-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestryproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
