# Generated by Django 5.2 on 2025-04-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestry', '0002_alter_forestryproduct_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='forestryproduct',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube videó URL'),
        ),
    ]
