# Generated by Django 5.2 on 2025-04-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hu', models.CharField(blank=True, help_text='A képhez tartozó rövid cím vagy felirat (opcionális).', max_length=200, verbose_name='Cím (Magyar)')),
                ('title_sk', models.CharField(blank=True, help_text='A képhez tartozó rövid cím vagy felirat szlovákul (opcionális).', max_length=200, verbose_name='Cím (Szlovák)')),
                ('image', models.ImageField(help_text='Válassza ki a feltöltendő képfájlt.', upload_to='gallery/', verbose_name='Képfájl')),
                ('alt_text_hu', models.CharField(blank=True, help_text='Rövid leírás a képről (akadálymentesítéshez és SEO-hoz, opcionális).', max_length=255, verbose_name='Alternatív szöveg (Magyar)')),
                ('alt_text_sk', models.CharField(blank=True, help_text='Rövid leírás a képről szlovákul (opcionális).', max_length=255, verbose_name='Alternatív szöveg (Szlovák)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Feltöltés ideje')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Meghatározza a képek megjelenési sorrendjét (kisebb szám előrébb).', verbose_name='Sorrend')),
            ],
            options={
                'verbose_name': 'Galéria kép',
                'verbose_name_plural': 'Galéria képek',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
