# Generated by Django 5.2 on 2025-04-19 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hu', models.CharField(max_length=100, verbose_name='Kategória neve (HU)')),
                ('name_sk', models.CharField(max_length=100, verbose_name='Kategória neve (SK)')),
                ('order', models.IntegerField(default=0, verbose_name='Sorrend')),
            ],
            options={
                'verbose_name': 'Kategória',
                'verbose_name_plural': 'Kategóriák',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_hu', models.CharField(max_length=200, verbose_name='Termék neve (HU)')),
                ('name_sk', models.CharField(max_length=200, verbose_name='Termék neve (SK)')),
                ('intro_hu', models.TextField(verbose_name='Bevezető szöveg (HU)')),
                ('intro_sk', models.TextField(verbose_name='Bevezető szöveg (SK)')),
                ('closing_text_hu', models.TextField(blank=True, verbose_name='Záró szöveg (HU)')),
                ('closing_text_sk', models.TextField(blank=True, verbose_name='Záró szöveg (SK)')),
                ('pdf_link_text_hu', models.CharField(default='Leírás itt!', max_length=100, verbose_name='PDF link szövege (HU)')),
                ('pdf_link_text_sk', models.CharField(default='[SK] Popis tu!', max_length=100, verbose_name='PDF link szövege (SK)')),
                ('pdf_url', models.CharField(blank=True, max_length=255, verbose_name='PDF URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main_app.category', verbose_name='Kategória')),
            ],
            options={
                'verbose_name': 'Termék',
                'verbose_name_plural': 'Termékek',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_hu', models.CharField(max_length=255, verbose_name='Jellemző (HU)')),
                ('feature_sk', models.CharField(max_length=255, verbose_name='Jellemző (SK)')),
                ('order', models.IntegerField(default=0, verbose_name='Sorrend')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='main_app.product', verbose_name='Termék')),
            ],
            options={
                'verbose_name': 'Jellemző',
                'verbose_name_plural': 'Jellemzők',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/xcmg/', verbose_name='Kép')),
                ('order', models.IntegerField(default=0, verbose_name='Sorrend')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.product', verbose_name='Termék')),
            ],
            options={
                'verbose_name': 'Termék kép',
                'verbose_name_plural': 'Termék képek',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_hu', models.CharField(max_length=255, verbose_name='Műszaki adat (HU)')),
                ('spec_sk', models.CharField(max_length=255, verbose_name='Műszaki adat (SK)')),
                ('order', models.IntegerField(default=0, verbose_name='Sorrend')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_specs', to='main_app.product', verbose_name='Termék')),
            ],
            options={
                'verbose_name': 'Műszaki adat',
                'verbose_name_plural': 'Műszaki adatok',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductWhyChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_hu', models.CharField(max_length=255, verbose_name='Ok (HU)')),
                ('reason_sk', models.CharField(max_length=255, verbose_name='Ok (SK)')),
                ('order', models.IntegerField(default=0, verbose_name='Sorrend')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose', to='main_app.product', verbose_name='Termék')),
            ],
            options={
                'verbose_name': 'Miért válassza',
                'verbose_name_plural': 'Miért válassza okok',
                'ordering': ['order'],
            },
        ),
    ]
