# Generated by Django 5.2 on 2025-04-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pdf_url',
        ),
        migrations.AddField(
            model_name='product',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='PDF Fájl'),
        ),
    ]
