# Generated by Django 5.2 on 2025-04-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_product_options_category_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hu', models.CharField(max_length=100, verbose_name='Név (HU)')),
                ('name_sk', models.CharField(max_length=100, verbose_name='Név (SK)')),
                ('description_hu', models.TextField(blank=True, verbose_name='Leírás (HU)')),
                ('description_sk', models.TextField(blank=True, verbose_name='Leírás (SK)')),
                ('image', models.ImageField(upload_to='main_sections/', verbose_name='Kép')),
                ('target_url_name', models.CharField(help_text="Add meg az app nevet és az URL nevet, pl. 'forestry:forestry_list'", max_length=100, verbose_name="Cél URL neve (pl. 'forestry:forestry_list')")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorrend')),
            ],
            options={
                'verbose_name': 'Főoldali Szekció',
                'verbose_name_plural': 'Főoldali Szekciók',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Partner neve')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Logó')),
                ('website_url', models.URLField(blank=True, help_text='A partner weboldalának teljes címe (pl. https://www.partnerdomain.hu)', null=True, verbose_name='Weboldal URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorrend')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partnerek',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productspec',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productwhychoose',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProductSpec',
        ),
        migrations.DeleteModel(
            name='ProductFeature',
        ),
        migrations.DeleteModel(
            name='ProductWhyChoose',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
