# Generated by Django 5.2 on 2025-04-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_mainsection_partner_remove_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hu', models.CharField(max_length=100, verbose_name='Termék neve (HU)')),
                ('name_sk', models.CharField(max_length=100, verbose_name='Termék neve (SK)')),
                ('description_hu', models.TextField(verbose_name='Leírás (HU)')),
                ('description_sk', models.TextField(verbose_name='Leírás (SK)')),
                ('image', models.ImageField(upload_to='popular_products/', verbose_name='Termék képe')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorrend')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
            ],
            options={
                'verbose_name': 'Népszerű Termék',
                'verbose_name_plural': 'Népszerű Termékek',
                'ordering': ['order'],
            },
        ),
    ]
