# Generated by Django 5.2 on 2025-04-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_popularproduct_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularproduct',
            name='product_url',
        ),
    ]
