# Generated by Django 5.2 on 2025-04-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_popularproduct_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularproduct',
            name='product_url',
            field=models.CharField(default='', help_text="Relatív URL a termék részletes oldalára (pl. 'xcmg-gepek/gep/1/')", max_length=255, verbose_name='Termék URL'),
        ),
    ]
