# Generated by Django 5.2 on 2025-04-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_popularproduct_product_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(1, 'Első termék'), (2, 'Második termék'), (3, 'Harmadik termék'), (4, 'Negyedik termék')], help_text='A termék pozíciója a főoldalon (1-4)', unique=True, verbose_name='Pozíció')),
                ('name_hu', models.CharField(max_length=100, verbose_name='Termék neve (HU)')),
                ('name_sk', models.CharField(max_length=100, verbose_name='Termék neve (SK)')),
                ('description_hu', models.TextField(verbose_name='Leírás (HU)')),
                ('description_sk', models.TextField(verbose_name='Leírás (SK)')),
                ('image', models.ImageField(upload_to='featured_products/', verbose_name='Termék képe')),
                ('product_url', models.CharField(default='', help_text="Relatív URL a termék részletes oldalára (pl. 'xcmg-gepek/gep/1/')", max_length=255, verbose_name='Termék URL')),
            ],
            options={
                'verbose_name': 'Népszerű Termék',
                'verbose_name_plural': 'Népszerű Termékek',
                'ordering': ['position'],
            },
        ),
        migrations.DeleteModel(
            name='PopularProduct',
        ),
    ]
