# Generated by Django 5.2 on 2025-04-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_featuredproduct_delete_popularproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainSection',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
