# Generated by Django 5.2 on 2025-04-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_delete_mainsection_delete_partner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedProduct',
        ),
    ]
