# Generated by Django 5.2 on 2025-04-21 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RampakCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hu', models.CharField(max_length=100, verbose_name='Kategória neve (HU)')),
                ('name_sk', models.CharField(max_length=100, verbose_name='Kategória neve (SK)')),
                ('order', models.IntegerField(default=0, verbose_name='Sorrend')),
            ],
            options={
                'verbose_name': 'Rámpa Kategória',
                'verbose_name_plural': 'Rámpa Kategóriák',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RampakProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hu', models.CharField(max_length=200, verbose_name='Termék neve (HU)')),
                ('name_sk', models.CharField(max_length=200, verbose_name='Termék neve (SK)')),
                ('intro_hu', models.TextField(blank=True, verbose_name='Bevezető szöveg (HU)')),
                ('intro_sk', models.TextField(blank=True, verbose_name='Bevezető szöveg (SK)')),
                ('closing_text_hu', models.TextField(blank=True, verbose_name='Záró szöveg (HU)')),
                ('closing_text_sk', models.TextField(blank=True, verbose_name='Záró szöveg (SK)')),
                ('pdf_link_text_hu', models.CharField(default='Leírás itt!', max_length=100, verbose_name='PDF link szövege (HU)')),
                ('pdf_link_text_sk', models.CharField(default='[SK] Popis tu!', max_length=100, verbose_name='PDF link szövege (SK)')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='rampak/pdfs/', verbose_name='PDF Fájl')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='YouTube videó URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='rampak.rampakcategory', verbose_name='Kategória')),
            ],
            options={
                'verbose_name': 'Rámpa',
                'verbose_name_plural': 'Rámpák',
                'ordering': ['category__order', 'name_hu'],
            },
        ),
        migrations.CreateModel(
            name='RampakProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_hu', models.CharField(max_length=255, verbose_name='Jellemző (HU)')),
                ('feature_sk', models.CharField(max_length=255, verbose_name='Jellemző (SK)')),
                ('order', models.IntegerField(default=0, verbose_name='Sorrend')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='rampak.rampakproduct', verbose_name='Termék')),
            ],
            options={
                'verbose_name': 'Rámpa Jellemző',
                'verbose_name_plural': 'Rámpa Jellemzők',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RampakProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rampak/pics/', verbose_name='Kép')),
                ('order', models.IntegerField(default=0, verbose_name='Sorrend')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rampak.rampakproduct', verbose_name='Termék')),
            ],
            options={
                'verbose_name': 'Rámpa Kép',
                'verbose_name_plural': 'Rámpa Képek',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RampakProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_hu', models.CharField(max_length=255, verbose_name='Műszaki adat (HU)')),
                ('spec_sk', models.CharField(max_length=255, verbose_name='Műszaki adat (SK)')),
                ('order', models.IntegerField(default=0, verbose_name='Sorrend')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_specs', to='rampak.rampakproduct', verbose_name='Termék')),
            ],
            options={
                'verbose_name': 'Rámpa Műszaki Adat',
                'verbose_name_plural': 'Rámpa Műszaki Adatok',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RampakProductWhyChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_hu', models.CharField(max_length=255, verbose_name='Ok (HU)')),
                ('reason_sk', models.CharField(max_length=255, verbose_name='Ok (SK)')),
                ('order', models.IntegerField(default=0, verbose_name='Sorrend')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose', to='rampak.rampakproduct', verbose_name='Termék')),
            ],
            options={
                'verbose_name': 'Rámpa Miért Válassza',
                'verbose_name_plural': 'Rámpa Miért Válassza Okok',
                'ordering': ['order'],
            },
        ),
    ]
